"""baseline: canonical spine per DATA_ARCHITECTURE.md

Revision ID: 7bafcc8bf60b
Revises:
Create Date: 2026-05-22 14:22:12.654026

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7bafcc8bf60b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("event_id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=True),
        sa.Column("job_id", sa.Text(), nullable=True),
        sa.Column("chain_id", sa.Text(), nullable=True),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index("ix_events_chain_created", "events", ["chain_id", "created_at"], unique=False)
    op.create_index("ix_events_job_created", "events", ["job_id", "created_at"], unique=False)
    op.create_index("ix_events_tenant_created", "events", ["tenant_id", "created_at"], unique=False)
    op.create_index("ix_events_type_created", "events", ["type", "created_at"], unique=False)
    op.create_table(
        "plans",
        sa.Column("plan_id", sa.Text(), nullable=False),
        sa.Column("plan_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("slo_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("plan_id"),
    )
    op.create_table(
        "tenants",
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id"),
    )
    op.create_table(
        "credentials",
        sa.Column("credentials_ref", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("scope_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("secret_payload", sa.LargeBinary(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rotated_from", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.tenant_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("credentials_ref"),
    )
    op.create_index("ix_credentials_expires", "credentials", ["expires_at"], unique=False)
    op.create_index("ix_credentials_tenant", "credentials", ["tenant_id"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("job_id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("spec_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("input_source", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("output_target", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.tenant_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.create_index("ix_jobs_status", "jobs", ["status"], unique=False)
    op.create_index("ix_jobs_tenant_created", "jobs", ["tenant_id", "created_at"], unique=False)
    op.create_table(
        "placement_alternatives",
        sa.Column("alternative_id", sa.Text(), nullable=False),
        sa.Column("plan_id", sa.Text(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("strategy", sa.String(length=32), nullable=False),
        sa.Column("pd_ratio", sa.Numeric(asdecimal=False), nullable=True),
        sa.Column("sizing_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("estimated_throughput_tps", sa.Numeric(asdecimal=False), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["plan_id"], ["plans.plan_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("alternative_id"),
    )
    op.create_index(
        "ix_placement_alternatives_plan_rank",
        "placement_alternatives",
        ["plan_id", "rank"],
        unique=False,
    )
    op.create_table(
        "resource_maps",
        sa.Column("resource_map_id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("snapshot_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.tenant_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("resource_map_id"),
    )
    op.create_index(
        "ix_resource_maps_snapshot_gin",
        "resource_maps",
        ["snapshot_json"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"snapshot_json": "jsonb_path_ops"},
    )
    op.create_index(
        "ix_resource_maps_tenant_captured",
        "resource_maps",
        ["tenant_id", "captured_at"],
        unique=False,
    )
    op.create_table(
        "chains",
        sa.Column("chain_id", sa.Text(), nullable=False),
        sa.Column("alternative_id", sa.Text(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("shape_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("parallelism_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("target_node", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["alternative_id"], ["placement_alternatives.alternative_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("chain_id"),
    )
    op.create_index(
        "ix_chains_alternative_role", "chains", ["alternative_id", "role"], unique=False
    )
    op.create_index("ix_chains_status", "chains", ["status"], unique=False)
    op.create_table(
        "decisions",
        sa.Column("decision_id", sa.Text(), nullable=False),
        sa.Column("job_id", sa.Text(), nullable=False),
        sa.Column("plan_id", sa.Text(), nullable=False),
        sa.Column("koi_version", sa.String(length=64), nullable=True),
        sa.Column("rationale_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.job_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["plan_id"], ["plans.plan_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("decision_id"),
    )
    op.create_index("ix_decisions_job", "decisions", ["job_id"], unique=False)
    op.create_index("ix_decisions_plan", "decisions", ["plan_id"], unique=False)
    op.create_table(
        "attempts",
        sa.Column("attempt_id", sa.Text(), nullable=False),
        sa.Column("chain_id", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason_code", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["chain_id"], ["chains.chain_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("attempt_id"),
    )
    op.create_index("ix_attempts_chain", "attempts", ["chain_id"], unique=False)
    op.create_table(
        "outcomes",
        sa.Column("outcome_id", sa.Text(), nullable=False),
        sa.Column("chain_id", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=True),
        sa.Column("metrics_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["chain_id"], ["chains.chain_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("outcome_id"),
    )
    op.create_index("ix_outcomes_chain", "outcomes", ["chain_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_outcomes_chain", table_name="outcomes")
    op.drop_table("outcomes")
    op.drop_index("ix_attempts_chain", table_name="attempts")
    op.drop_table("attempts")
    op.drop_index("ix_decisions_plan", table_name="decisions")
    op.drop_index("ix_decisions_job", table_name="decisions")
    op.drop_table("decisions")
    op.drop_index("ix_chains_status", table_name="chains")
    op.drop_index("ix_chains_alternative_role", table_name="chains")
    op.drop_table("chains")
    op.drop_index("ix_resource_maps_tenant_captured", table_name="resource_maps")
    op.drop_index(
        "ix_resource_maps_snapshot_gin",
        table_name="resource_maps",
        postgresql_using="gin",
        postgresql_ops={"snapshot_json": "jsonb_path_ops"},
    )
    op.drop_table("resource_maps")
    op.drop_index("ix_placement_alternatives_plan_rank", table_name="placement_alternatives")
    op.drop_table("placement_alternatives")
    op.drop_index("ix_jobs_tenant_created", table_name="jobs")
    op.drop_index("ix_jobs_status", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index("ix_credentials_tenant", table_name="credentials")
    op.drop_index("ix_credentials_expires", table_name="credentials")
    op.drop_table("credentials")
    op.drop_table("tenants")
    op.drop_table("plans")
    op.drop_index("ix_events_type_created", table_name="events")
    op.drop_index("ix_events_tenant_created", table_name="events")
    op.drop_index("ix_events_job_created", table_name="events")
    op.drop_index("ix_events_chain_created", table_name="events")
    op.drop_table("events")
    # ### end Alembic commands ###
